#!/usr/bin/env python3
"""Mojo GPU kernels -> loadable sm_121 PTX / cubin + manifest.json (the NVIDIA twin of hipmodule/mojo2hsaco.py).

Route: `mojo build --emit object --target-accelerator sm_121 <file>.mojo` leaves, per instantiated
kernel, one complete PTX module (text, `.version 8.8 / .target sm_121a`, one `.entry`) embedded in
the host object. (On AMD the object embeds finished ELF code objects; on NVIDIA it embeds PTX, so
the driver JITs it at cuModuleLoadData, or `ptxas` can make a cubin ahead of time, which this script
does when ptxas is found.) Every kernel must be instantiated by a host function in the file
(enqueue_function[kernel]) or Mojo does not compile it. For each kernel this writes
  <outdir>/<short>.ptx, <outdir>/<short>.cubin (ptxas -arch sm_121a, if available), and an entry in
  <outdir>/manifest.json: symbol (cuModuleGetFunction name) and the .param layout (index, ptx type,
  size, offset, pointer or not). cuLaunchKernel's kernelParams form takes one pointer per param in
  this order; the offsets are what the packed `extra` buffer form (CU_LAUNCH_PARAM_BUFFER_POINTER)
  needs. There are no hidden arguments on NVIDIA.

usage: mojo2cubin.py kernels.mojo outdir [--arch sm_121] [--mojo mojo] [--ptxas ptxas] [--no-cubin]
"""
import argparse, json, os, re, shutil, subprocess, sys, tempfile

SIZES = {"u8": 1, "s8": 1, "b8": 1, "u16": 2, "s16": 2, "b16": 2, "f16": 2, "u32": 4, "s32": 4, "b32": 4,
         "f32": 4, "u64": 8, "s64": 8, "b64": 8, "f64": 8}


def carve_ptx(blob):
    """Return [str] of every PTX module (each starts at `// Generated by` or `.version`, ends at NUL)."""
    out = []
    for m in re.finditer(rb"\.version [0-9.]+\n\.target sm_\w+\n", blob):
        s = m.start()
        e = blob.find(b"\0", s)
        out.append(blob[s:e if e >= 0 else len(blob)].decode())
    return out


def parse_entries(ptx):
    """[(symbol, [param dict])] for each `.entry` of a PTX module."""
    res = []
    for m in re.finditer(r"\.entry\s+(\w+)\s*\((.*?)\)\s*\n\s*(?:\.\w+[^\n{]*\n\s*)*\{", ptx, re.S):
        sym, body = m.group(1), m.group(2)
        params, off = [], 0
        for i, line in enumerate(l.strip().rstrip(",") for l in body.split("\n") if l.strip()):
            pm = re.match(r"\.param\s+(.*?)\s+(\w+)(?:\[(\d+)\])?$", line)
            if not pm:
                raise ValueError(f"cannot parse param: {line!r}")
            attrs, _name, count = pm.groups()
            ty = re.search(r"\.(u8|s8|b8|u16|s16|b16|f16|u32|s32|b32|f32|u64|s64|b64|f64)\b", attrs).group(1)
            al = re.search(r"\.align\s+(\d+)", attrs)
            elem = SIZES[ty]
            size = elem * int(count) if count else elem
            align = max(int(al.group(1)) if al and count else 1, elem)
            off = (off + align - 1) // align * align
            params.append({"index": i, "type": ty, "offset": off, "size": size, "ptr": ".ptr" in attrs})
            off += size
        res.append((sym, params))
    return res


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src"); ap.add_argument("outdir")
    ap.add_argument("--arch", default="sm_121"); ap.add_argument("--mojo", default="mojo")
    ap.add_argument("--ptxas", default=shutil.which("ptxas") or "/usr/local/cuda/bin/ptxas")
    ap.add_argument("--no-cubin", action="store_true")
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)
    stem = os.path.splitext(os.path.basename(a.src))[0]
    defs = re.findall(r"^def\s+(\w+)\s*\(", open(a.src).read(), re.M)
    with tempfile.TemporaryDirectory() as td:
        obj = os.path.join(td, stem + ".o")
        r = subprocess.run([a.mojo, "build", "--emit", "object", "--target-accelerator", a.arch,
                            a.src, "-o", obj], capture_output=True, text=True)
        if r.returncode:
            sys.stderr.write(r.stderr); sys.exit(r.returncode)
        mods = carve_ptx(open(obj, "rb").read())
    manifest = {"arch": a.arch, "source": os.path.basename(a.src), "kernels": []}
    for ptx in mods:
        target = re.search(r"\.target (\w+)", ptx).group(1)
        for sym, params in parse_entries(ptx):
            cands = [d for d in defs if sym.startswith(f"{stem}_{d}_")]
            short = max(cands, key=len) if cands else sym
            open(os.path.join(a.outdir, short + ".ptx"), "w").write(ptx)
            ent = {"name": short, "symbol": sym, "ptx": short + ".ptx", "target": target,
                   "param_size": (params[-1]["offset"] + params[-1]["size"]) if params else 0, "params": params}
            if not a.no_cubin and os.path.exists(a.ptxas):
                cub = os.path.join(a.outdir, short + ".cubin")
                r = subprocess.run([a.ptxas, f"-arch={target}", os.path.join(a.outdir, short + ".ptx"),
                                    "-o", cub], capture_output=True, text=True)
                if r.returncode:
                    sys.stderr.write(r.stderr); sys.exit(r.returncode)
                ent["cubin"] = short + ".cubin"
            manifest["kernels"].append(ent)
    json.dump(manifest, open(os.path.join(a.outdir, "manifest.json"), "w"), indent=1)
    for k in manifest["kernels"]:
        print(k["name"], k["ptx"], k.get("cubin", "-"), [(p["offset"], p["size"], p["type"]) for p in k["params"]])


main()
